name: poultrynow
description: "Poultry farm management app"
publish_to: 'none'
version: 1.0.40+40

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Your packages
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.4.2
  path_provider: ^2.1.4
  file_picker: ^8.0.4
  csv: ^6.0.0   # <-- ADD THIS LINE FOR IMPORT/EXPORT

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
