flutter:
  uses-material-design: true

  # App Icon for launcher
  assets:
    - assets/icon.png

    # All images folder
    - assets/images/

    # If you add more folders later just add them here
    # - assets/data/
